name: Main Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: prod
    secrets:
      NESTED_SECRET: ${{ secrets.MY_SECRET }}
