name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      NESTED_SECRET:
        required: true

jobs:
  do-something:
    runs-on: ubuntu-latest
    secrets: inherit
    steps:
    - name: Check secret presence
      run: |
        if [ -z "$NESTED_SECRET" ]; then
          echo "Secret is empty!"
        else
          echo "Secret is set, length: ${#NESTED_SECRET}"
        fi
  
    - name: Show env and secret
      run: |
        echo "Environment is ${{ inputs.environment }}"
        echo "Secret length: ${#NESTED_SECRET}" # avoid echoing secrets directly!
